# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

parameters:
  - name: application_client_ID
    type: string
    default: "e1005577-3e06-447d-b7e9-61c897ee73cc"

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'sub-up-atlas-mgmt(2)(93c2ecdc-d65f-4cbc-af13-71e3b5317f67)'
    ScriptType: 'InlineScript'
    Inline: |
      Write-Host 'Starting secret renewal'
           
           
           Write-Host 'Retrieving Logic App Url'
           $resourceGroup = 'rg-up-atlas-mgmt'
           $logicAppName = 'renewAppRegistrations'
           $triggerName = 'manual'
           $logicAppCallbackUrl = Get-AzLogicAppTriggerCallbackUrl -ResourceGroupName $resourceGroup -Name $logicAppName -TriggerName $triggerName
           $logicAppUrl = $logicAppCallbackUrl.Value
           
           $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
           $headers.Add("Content-Type", "application/json")

           $jsonData = @{appID = "${{ parameters.application_client_ID }}"
            } | ConvertTo-Json
           
           $response = Invoke-RestMethod $logicAppUrl -Method 'POST' -Headers $headers -Body $jsonData 
           #$response = Invoke-RestMethod $logicAppUrl -Method 'POST' -Headers $headers -Body $body -ContentType 'text/plain; charset=utf-8'
          
           Write-Host 'Upload to SharePoint via Logic App complete'
           Write-Host $response 
    azurePowerShellVersion: 'LatestVersion'


